name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - AIWintermuteAI
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you do, however, make sure you have done the following.

  - type: checkboxes
    id: googled
    attributes:
      options:
        - label: I used Google/Bing/other search engines to thoroughly research my question and DID NOT find any suitable answers
          required: true

        - label: Additionally I went through the issues in this repository/MaixPy/Tensorflow repositories and DID NOT find any suitable answers
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, with screenshots/models/videos if necessary.
      value: |
            **To Reproduce**
            Steps to reproduce the behavior:
            1. Go to '...'
            2. Click on '....'
            3. Scroll down to '....'
            4. See error
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: What platform are you running the code on.
      value: |
            - Device: [e.g. Raspberry Pi 4 or M5 StickV]
            - OS/firmware: [e.g. Raspbian OS 32bit kernel version ...]
            - Version/commit number of aXeleRate: [e.g. d1816f5]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

