blank_issues_enabled: false
contact_links:
  - name: Google
    url: https://google.com/
    about: Please find answers to general questions,i.e "what are anchors", "how is mAP calculated", "my cat coughing up fur can you help please" HERE.